## Convert to Massey

Take CSV of Google Sheets and convert to input data for Massey method

In [3]:
import pandas as pd
import math 
import numpy as np 

teamFilename = '24teams.txt'
gameFilename = '24games.txt'

# Hardcode number of problems
numberOfProblems = 15

# Import the CSV file 
df = pd.read_csv (r'All olympiads 2024.csv')
df.head()

           Full name  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  Total
0       Сахипов Амир  7  3  7  7  7  7  7  7  0   0   0   7   7   0   0   66.0
1     Шарел Марғұлан  7  7  7  7  0  7  7  7  0   0   0   7   7   0   1   64.0
2      Юркевич Мирон  7  7  2  6  0  7  7  0  0   1   7   7   7   3   0   61.0
3         Даутов Жан  7  7  0  6  7  2  7  3  0   0   0   7   7   7   0   60.0
4  Аманжолов Амирлан  7  0  0  7  7  1  7  7  0   0   0   7   7   7   0   57.0

### Create team file from CSV data

In [6]:
teamsList = list(np.array(range(numberOfProblems)) + 1) + list(df['Full name'])

# Print the header of the dataframe
#print (df)

# Write teams file
teamsFile = open(teamFilename, "w")
for i in range(len(teamsList)):
    teamsFile.write('%3i, %s\n' %(i+1,teamsList[i]))
teamsFile.close()

df.head()

           Full name  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  Total
0       Сахипов Амир  7  3  7  7  7  7  7  7  0   0   0   7   7   0   0   66.0
1     Шарел Марғұлан  7  7  7  7  0  7  7  7  0   0   0   7   7   0   1   64.0
2      Юркевич Мирон  7  7  2  6  0  7  7  0  0   1   7   7   7   3   0   61.0
3         Даутов Жан  7  7  0  6  7  2  7  3  0   0   0   7   7   7   0   60.0
4  Аманжолов Амирлан  7  0  0  7  7  1  7  7  0   0   0   7   7   7   0   57.0

### Create game file from CSV data

In [9]:
gamesFile = open(gameFilename, "w")

numberOfRows = df.shape[0]
for i in range(numberOfRows):
    masseyDateDay = 111111 # I don't believe we use this so it's a bogus value
    dateString='20101225'    # I don't believe we use this so it's a bogus value
    team1Loc = 0
    team2Loc = 0
    
    # Loop over problem columns
    for k in range(numberOfProblems):
        team1 = k+1
        team2 = teamsList.index(df['Full name'][i]) + 1 
        problemScore = df[str(k+1)][i]  # this is the score on problem (k+1) for player j
        # score: 0-2: problem wins, 3-4: draw, 5-7: player wins
        if problemScore < 3: 
            team1Score = 3 - problemScore 
            team2Score = 0
        elif problemScore < 5: 
            team1Score = 1
            team2Score = 1
        else: 
            team2Score = problemScore - 4
            team1Score = 0 
        if team1Score >= team2Score: 
            gamesFile.write('%6d,%8s,%2d,%1d,%6.4f,%2d,%1d,%6.4f\n' % (masseyDateDay,dateString,team1,team1Loc,team1Score,team2,team2Loc,team2Score))    
        else: 
            gamesFile.write('%6d,%8s,%2d,%1d,%6.4f,%2d,%1d,%6.4f\n' % (masseyDateDay,dateString,team2,team2Loc,team2Score,team1,team1Loc,team1Score))    

gamesFile.close()

In [11]:
print("A"+str(1))

A1